global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'citibike-app'
    static_configs:
#      - targets: ['host.docker.internal:8081']
      - targets: ['192.168.50.183:8081']
        labels:
          application: 'citibike-kstreams'
          version: '1.0.0'
    # Use host.docker.internal to reach the host machine from Docker
    # On Linux, if host.docker.internal doesn't work, use the host's IP address
    # or add extra_hosts in docker-compose.yml

