global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'citibike-app'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'citibike-kstreams'
          version: '1.0.0'
    # For macOS/Linux, use host.docker.internal
    # For Linux, you may need to use the host IP or add extra_hosts in docker-compose

